# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af8c400b7871cd2911cc673f6b2ca8e3e3cc3cfcd1c2e3483b8ddac41a897f78b566c126d19173cad36cffe3a5955cb828f714a1b832a29040a8ad4a614a3e8

test:
  secret_key_base: 072b64e5227ded46814ef10e631f87e64fc0df3224a9b59d4446475b7a9b9f3c5d40ddfa6bef877a69d7ae08f0f82d3954f318f4397e63597272b7e09ed81f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
